DROP TABLE IF EXISTS LOG_WORKOUT;
DROP TABLE IF EXISTS `JOINS`;
DROP TABLE IF EXISTS FRIENDSHIP;
DROP TABLE IF EXISTS WORKOUT_GROUP;
DROP TABLE IF EXISTS HAS;
DROP TABLE IF EXISTS CARDIO;
DROP TABLE IF EXISTS STRENGTH;
DROP TABLE IF EXISTS WORKOUT_SESSION;
DROP TABLE IF EXISTS EXERCISE_INSTANCE;
DROP TABLE IF EXISTS EXERCISE_TYPE;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
	USER_ID INT AUTO_INCREMENT,
	F_NAME VARCHAR(50),
	L_NAME VARCHAR(50),
	COMP_ID VARCHAR(7),
	PASSWORD VARCHAR(255),
	YEAR INT,
	PRIMARY KEY (USER_ID)
);

CREATE TABLE EXERCISE_TYPE (
	EXERCISE_ID INT AUTO_INCREMENT,
	EXERCISE_NAME VARCHAR(100),
	PRIMARY KEY (EXERCISE_ID)
);

CREATE TABLE EXERCISE_INSTANCE (
	INSTANCE_ID INT AUTO_INCREMENT,
	EXERCISE_ID INT,
	DATE DATETIME,
	PRIMARY KEY(INSTANCE_ID),
	FOREIGN KEY (EXERCISE_ID) REFERENCES EXERCISE_TYPE(EXERCISE_ID)
);

CREATE TABLE WORKOUT_SESSION (
	SESSION_ID INT AUTO_INCREMENT,
	DATE DATETIME,
	LOCATION VARCHAR(120),
	PRIMARY KEY (SESSION_ID)
);

CREATE TABLE HAS (
	INSTANCE_ID INT,
	SESSION_ID INT,
	PRIMARY KEY (INSTANCE_ID, SESSION_ID),
	FOREIGN KEY (INSTANCE_ID) REFERENCES EXERCISE_INSTANCE(INSTANCE_ID),
	FOREIGN KEY(SESSION_ID) REFERENCES WORKOUT_SESSION(SESSION_ID)
);

CREATE TABLE WORKOUT_GROUP (
	GROUP_ID INT AUTO_INCREMENT,
	CREATOR_ID INT,
	GROUP_NAME VARCHAR(100),
	NUMBER_OF_MEMBERS INT,
	PRIMARY KEY (GROUP_ID),
	FOREIGN KEY (CREATOR_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE STRENGTH (
	INSTANCE_ID INT,
	WEIGHT FLOAT CHECK (WEIGHT > 0),
	SETS INT CHECK (SETS > 0),
	REPS INT CHECK (REPS > 0),
	PRIMARY KEY(INSTANCE_ID)
);

CREATE TABLE CARDIO (
	INSTANCE_ID INT,
	DISTANCE FLOAT,
	DURATION FLOAT,
	PRIMARY KEY(INSTANCE_ID)
);

CREATE TABLE FRIENDSHIP (
	USER_ID1 INT,
	USER_ID2 INT,
	PRIMARY KEY (USER_ID1, USER_ID2),
	FOREIGN KEY (USER_ID1) REFERENCES USERS(USER_ID),
	FOREIGN KEY (USER_ID2) REFERENCES USERS(USER_ID)
);

CREATE TABLE JOINS (
	USER_ID INT,
	GROUP_ID INT,
	PRIMARY KEY (USER_ID, GROUP_ID),
	FOREIGN KEY (GROUP_ID) REFERENCES WORKOUT_GROUP(GROUP_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE LOG_WORKOUT (
	USER_ID INT,
	SESSION_ID INT,
	PRIMARY KEY(USER_ID, SESSION_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY (SESSION_ID) REFERENCES WORKOUT_SESSION(SESSION_ID)
);


INSERT INTO USERS (f_name, l_name, comp_id, password, year) VALUES ("Alston", "Hou", "epe9ev", "alston123", 2026);
INSERT INTO USERS (f_name, l_name, comp_id, password, year) VALUES ("Adnan", "Murtaza", "enn6qy", "adnan123", 2026);
INSERT INTO USERS (f_name, l_name, comp_id, password, year) VALUES ("Ben", "Chang", "bnw6yx", "ben123", 2026);
INSERT INTO USERS (f_name, l_name, comp_id, password, year) VALUES ("Kenny", "Nguyen", "vrv6sf", "kenny123", 2026);

INSERT INTO EXERCISE_TYPE (EXERCISE_NAME) VALUES ("Pull Ups");
INSERT INTO EXERCISE_TYPE (EXERCISE_NAME) VALUES ("Bench Press");
INSERT INTO EXERCISE_TYPE (EXERCISE_NAME) VALUES ("Running");
INSERT INTO EXERCISE_TYPE (EXERCISE_NAME) VALUES ("Swimming");

INSERT INTO EXERCISE_INSTANCE (exercise_id, `date`) VALUES (1, '2025-10-26 22:05:00');
INSERT INTO EXERCISE_INSTANCE (exercise_id, `date`) VALUES (2, '2025-10-26 22:10:00');
INSERT INTO EXERCISE_INSTANCE (exercise_id, `date`) VALUES (1, '2025-10-24 15:05:00');
INSERT INTO EXERCISE_INSTANCE (exercise_id, `date`) VALUES (2, '2025-10-24 15:10:00');
INSERT INTO EXERCISE_INSTANCE (exercise_id, `date`) VALUES (2, '2025-10-23 14:05:00');
INSERT INTO EXERCISE_INSTANCE (exercise_id, `date`) VALUES (2, '2025-10-21 13:05:00');
INSERT INTO EXERCISE_INSTANCE (exercise_id, `date`) VALUES (4, '2025-10-23 14:10:00');
INSERT INTO EXERCISE_INSTANCE (exercise_id, `date`) VALUES (3, '2025-10-21 13:10:00');

INSERT INTO STRENGTH (instance_id, weight, sets, reps) VALUES (1, 25, 3, 10);
INSERT INTO STRENGTH (instance_id, weight, sets, reps) VALUES (2, 225, 3, 5);
INSERT INTO STRENGTH (instance_id, weight, sets, reps) VALUES (3, 10, 3, 6);
INSERT INTO STRENGTH (instance_id, weight, sets, reps) VALUES (4, 135, 3, 5);
INSERT INTO STRENGTH (instance_id, weight, sets, reps) VALUES (5, 135, 3, 5);
INSERT INTO STRENGTH (instance_id, weight, sets, reps) VALUES (6, 200, 4, 5);

INSERT INTO CARDIO (instance_id, distance, duration) VALUES (7, 100, 59);
INSERT INTO CARDIO (instance_id, distance, duration) VALUES (8, 1000, 300);

INSERT INTO WORKOUT_SESSION VALUES (1, '2025-10-26 22:00:00', "AFC");
INSERT INTO WORKOUT_SESSION VALUES (2, '2025-10-24 15:00:00', "SRC");
INSERT INTO WORKOUT_SESSION VALUES (3, '2025-10-23 14:00:00', "MEM");
INSERT INTO WORKOUT_SESSION VALUES (4, '2025-10-21 13:00:00', "AFC");

INSERT INTO HAS (instance_id, session_id) VALUES (1, 1);
INSERT INTO HAS (instance_id, session_id) VALUES (2, 1);
INSERT INTO HAS (instance_id, session_id) VALUES (3, 2);
INSERT INTO HAS (instance_id, session_id) VALUES (4, 2);
INSERT INTO HAS (instance_id, session_id) VALUES (5, 3);
INSERT INTO HAS (instance_id, session_id) VALUES (6, 4);
INSERT INTO HAS (instance_id, session_id) VALUES (7, 3);
INSERT INTO HAS (instance_id, session_id) VALUES (8, 4);

INSERT INTO WORKOUT_GROUP (group_id, creator_id, group_name) VALUES (1, 1, "Killer Abs");

INSERT INTO FRIENDSHIP (user_id1, user_id2) VALUES (1, 2);
INSERT INTO FRIENDSHIP (user_id1, user_id2) VALUES (2, 1);
INSERT INTO FRIENDSHIP (user_id1, user_id2) VALUES (3, 4);
INSERT INTO FRIENDSHIP (user_id1, user_id2) VALUES (4, 3);

INSERT INTO JOINS (user_id, group_id) VALUES (1, 1);
INSERT INTO JOINS (user_id, group_id) VALUES (2, 1);
INSERT INTO JOINS (user_id, group_id) VALUES (3, 1);
INSERT INTO JOINS (user_id, group_id) VALUES (4, 1);


INSERT INTO LOG_WORKOUT (user_id, SESSION_ID) VALUES (1, 1);
INSERT INTO LOG_WORKOUT (user_id, SESSION_ID) VALUES (2, 2);
INSERT INTO LOG_WORKOUT (user_id, SESSION_ID) VALUES (3, 3);
INSERT INTO LOG_WORKOUT (user_id, SESSION_ID) VALUES (4, 4);


UPDATE WORKOUT_GROUP SET NUMBER_OF_MEMBERS = 4 WHERE GROUP_NAME = "Killer Abs";

-- Copy/Pasted from the SQL terminal, DELIMITERS added in case this file needs it. If errors arise, remove all DELIMITER and $$ statements, as well as the last semicolon.
DELIMITER $$

CREATE TRIGGER ENFORCE_GROUP_SIZE_CONSISTENCY
AFTER INSERT ON JOINS
FOR EACH ROW
BEGIN
  UPDATE WORKOUT_GROUP
  SET NUMBER_OF_MEMBERS = NUMBER_OF_MEMBERS + 1
  WHERE GROUP_ID = NEW.GROUP_ID;
END$$

DELIMITER ;